Source/Web/PremierLeagueApp.Web/Controllers/AddNewsController.cs
namespace MvcTemplate.Web.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    using PagedList;

    using PremierLeagueApp.Data;
    using PremierLeagueApp.Data.Models;
    using PremierLeagueApp.Web.ViewModels.Home;
    using Microsoft.AspNet.Identity;
    public class AddNewsController : Controller
    {
        private const int PageSize = 12;

        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index(int page = 1)
        {
            var news = this.db.News.Include(n => n.Club).OrderByDescending(x => x.Id).ToList().ToPagedList(page, PageSize);

            return this.View(news);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            News news = this.db.News.Find(id);
            if (news == null)
            {
                return this.HttpNotFound();
            }

            return this.View(news);
        }

        public ActionResult Create()
        {
            this.ViewData["Teams"] = this.db.Clubs.OrderBy(x => x.Name)
                .Select(x => new SelectListItem
                {
                    Text = x.Name, Value = x.Id.ToString()
                });

            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(NewsViewModel news)
        {
            var article = new News();
            if (this.ModelState.IsValid)
            {
                article.ImageUrl = news.ImageUrl;
                article.Title = news.Title;
                article.Content = news.Content;
                article.CreatedOn = DateTime.Now;
                article.ClubId = news.ClubId;
                article.CreatorId = this.User.Identity.GetUserId();
                this.db.News.Add(article);
                this.db.SaveChanges();

                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(news);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            News news = this.db.News.Find(id);
            if (news == null)
            {
                return this.HttpNotFound();
            }

            this.ViewBag.ClubId = new SelectList(this.db.Clubs, "Id", "Name", news.ClubId);
            return this.View(news);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(News news)
        {
            if (this.ModelState.IsValid)
            {
                news.ModifiedOn = DateTime.Now;
                this.db.Entry(news).State = EntityState.Modified;
                this.db.SaveChanges();

                return this.RedirectToAction("Index");
            }

            this.ViewBag.ClubId = new SelectList(this.db.Clubs, "Id", "Name", news.ClubId);
            return this.View(news);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            News news = this.db.News.Find(id);
            if (news == null)
            {
                return this.HttpNotFound();
            }

            return this.View(news);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            News news = this.db.News.Find(id);
            this.db.News.Remove(news);
            this.db.SaveChanges();
            return this.RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.db.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

Source/Web/PremierLeagueApp.Web/Views/AddNews/Create.cshtml
@model PremierLeagueApp.Web.ViewModels.Home.NewsViewModel

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "AddNews", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <br />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Content, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClubId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.ClubId, (IEnumerable<SelectListItem>)this.ViewData["Teams"], new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClubId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section styles {
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        tinymce.init({
            selector: '#Content'
        });
    </script>
}

Source/Web/PremierLeagueApp.Web/Views/AddNews/Delete.cshtml
@model PremierLeagueApp.Data.Models.News

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>News</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Club.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Club.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeletedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeletedOn)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Source/Web/PremierLeagueApp.Web/Views/AddNews/Details.cshtml
@model PremierLeagueApp.Data.Models.News

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>News</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Club.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Club.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeletedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeletedOn)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Source/Web/PremierLeagueApp.Web/Views/AddNews/Edit.cshtml
@model PremierLeagueApp.Data.Models.News

@{
    ViewBag.Title = "Edit";
}

<h3>Edit</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClubId, "ClubId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClubId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClubId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section styles {
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        tinymce.init({
            selector: '#Content'
        });
    </script>
}

Source/Web/PremierLeagueApp.Web/Views/AddNews/Index.cshtml
@model PagedList.IPagedList<PremierLeagueApp.Data.Models.News>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}

<h4>
    @if (this.User.Identity.IsAuthenticated)
    {
        @Html.ActionLink("Create", "Create")
    }
</h4>
<table class="table">
    <tr>
        <th class="col-md-1">
            @Html.DisplayNameFor(model => model.First().Id)
        </th>
        <th class="col-md-1">
            @Html.DisplayNameFor(model => model.First().Club)
        </th>
        <th class="col-md-1">
            @Html.DisplayNameFor(model => model.First().ImageUrl)
        </th>
        <th class="col-md-1">
            @Html.DisplayNameFor(model => model.First().Title)
        </th>
        <th class="col-md-3">
            @Html.DisplayNameFor(model => model.First().Content)
        </th>
        <th class="col-md-1">
            @Html.DisplayNameFor(model => model.First().CreatedOn)
        </th>
        <th class="col-md-1">
            @Html.DisplayNameFor(model => model.First().ModifiedOn)
        </th>
        <th class="col-md-1">
            @Html.DisplayNameFor(model => model.First().IsDeleted)
        </th>
        <th class="col-md-1">
            @Html.DisplayNameFor(model => model.First().DeletedOn)
        </th>
        <th class="col-md-1">
            Options
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Club.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                <div id="content">
                    @Html.DisplayFor(modelItem => item.Content)
                </div>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModifiedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDeleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeletedOn)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id })<br />
                @Html.ActionLink("Details", "Details", new { id = item.Id })<br />
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<br />
@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))